### ISSUE TITLE
Compilation issue

### ISSUE THREAD

**Issue by miseri** [EricssonResearch/scream#29]
I was following the instructions at https://github.com/EricssonResearch/scream/tree/master/code/gscream and came across a compilation issue: 
The ScreamRx.h header in scream/code/gscream/gst-gscreamrx/gst-plugin/src needs to be changed to a symbolic link pointing to ../../../../ScreamRx.h similar to the .cpp file. (the header is out of sync with the source file) and autogen.sh fails to compile.

**Comment by mirabilos** [comment]
I noticed the same and provided the fix as pull request.

However, the gscream code will need more changes to build (e.g. the new `isMark` parameter in `addTransmitted`).
