### ISSUE TITLE
QUESTION: Real-World Projects

### ISSUE THREAD

**Issue by pedroVRVIU** [EricssonResearch/scream#49]
Hi everyone (contributors),

I am learning about congestion control algorithms in the industry and found your paper and GitHub implementation, and I was wondering if you have real-world projects that use SCReAM and where I can find more information, because I am really interested in understanding how it behaves in real-life use cases.

Kind regards,
Pedro

**Comment by pedroVRVIU** [comment]
Dear @IngJohEricsson 

I apologize for tagging you into this issue, but it seems to me that you're the main contributor to this project. If you could find some time to answer my question, I would be very grateful.

Kind regards,
Pedro

**Comment by IngJohEricsson** [comment]
Hi
Yes. There are a bunch of real-life use cases with SCReAM, they are mainly connected to the benchmarking and showcasing of L4S. You can look for instance at the links below. 
There are a few other implementations, but as they are connected to various ongoing project I cannot expose them. 

Remote controlled RC-CAR : https://www.linkedin.com/posts/ingemar-johansson-27313710_hi-a-demonstration-of-remote-control-of-an-activity-6995671117155721216-dWXj?utm_source=share&utm_medium=member_desktop 

Cloud gaming demo : https://www.ericsson.com/en/news/2021/10/dt-and-ericsson-successfully-test-new-5g-low-latency-feature-for-time-critical-applications

**Comment by pedroVRVIU** [comment]
Hi
Thank you for the quick reply.

Is it possible to create Pull Requests? I have been fixing some memory leaks, and other issues with the code as I am trying to learn about it. Since I don't want it to go to waste, might as well contribute somehow.

Thanks,
Pedro

(will close issue after the answer if not closed by someone else)
